// shared/data.js
// 全デザイン共通のデータ定義（サンプルゲーム・ジャンル・機種・ステータス・i18n）
// window 名前空間にぶら下げて、各 jsx から参照する。

window.SAMPLE_GAMES = [
  { id: 1,  title: "Neon Drifters",        title_en: "Neon Drifters",        genre: "racing",     platform: "PS5",     released: "2024-03-14", playtime: 42,  status: "cleared", rating: 5, color: "#ff3da5", spineStyle: "stripe" },
  { id: 2,  title: "クリスタル・ソナタ",    title_en: "Crystal Sonata",       genre: "rpg",        platform: "Switch",  released: "2023-11-09", playtime: 86,  status: "cleared", rating: 5, color: "#7b5cff", spineStyle: "block" },
  { id: 3,  title: "Hexblade Saga",        title_en: "Hexblade Saga",        genre: "rpg",        platform: "PC",      released: "2022-06-22", playtime: 124, status: "cleared", rating: 4, color: "#ffd23f", spineStyle: "split" },
  { id: 4,  title: "深海の灯",              title_en: "Lantern of the Deep",  genre: "adventure",  platform: "PS5",     released: "2024-08-30", playtime: 18,  status: "playing", rating: 4, color: "#00d9ff", spineStyle: "wave" },
  { id: 5,  title: "Pixel Pioneers",       title_en: "Pixel Pioneers",       genre: "strategy",   platform: "PC",      released: "2021-04-15", playtime: 210, status: "cleared", rating: 5, color: "#ff7a3d", spineStyle: "grid" },
  { id: 6,  title: "Star Captain Lyra",    title_en: "Star Captain Lyra",    genre: "shooter",    platform: "Xbox",    released: "2024-01-25", playtime: 31,  status: "cleared", rating: 4, color: "#3dffb5", spineStyle: "stripe" },
  { id: 7,  title: "Forgotten Wells",      title_en: "Forgotten Wells",      genre: "rpg",        platform: "PC",      released: "2025-02-11", playtime: 8,   status: "playing", rating: 3, color: "#c084fc", spineStyle: "block" },
  { id: 8,  title: "刀と霧",               title_en: "Steel and Mist",       genre: "action",     platform: "PS5",     released: "2023-05-19", playtime: 64,  status: "cleared", rating: 5, color: "#e63946", spineStyle: "split" },
  { id: 9,  title: "Sprocket City",        title_en: "Sprocket City",        genre: "simulation", platform: "Switch",  released: "2022-09-02", playtime: 92,  status: "cleared", rating: 4, color: "#ffd23f", spineStyle: "grid" },
  { id: 10, title: "Bunny Hop GP",         title_en: "Bunny Hop GP",         genre: "racing",     platform: "Switch",  released: "2020-07-10", playtime: 25,  status: "cleared", rating: 4, color: "#ff3da5", spineStyle: "stripe" },
  { id: 11, title: "Echoes of Halcyon",    title_en: "Echoes of Halcyon",    genre: "adventure",  platform: "PC",      released: "2023-10-20", playtime: 0,   status: "backlog", rating: 0, color: "#00d9ff", spineStyle: "wave" },
  { id: 12, title: "Tower of Iron",        title_en: "Tower of Iron",        genre: "action",     platform: "PS4",     released: "2019-12-05", playtime: 47,  status: "cleared", rating: 4, color: "#a3a3a3", spineStyle: "block" },
  { id: 13, title: "甘味喫茶ストーリー",    title_en: "Sweet Cafe Story",     genre: "simulation", platform: "Switch",  released: "2024-06-12", playtime: 38,  status: "playing", rating: 4, color: "#ff9eb5", spineStyle: "split" },
  { id: 14, title: "Rift Runners",         title_en: "Rift Runners",         genre: "shooter",    platform: "PC",      released: "2022-11-18", playtime: 156, status: "cleared", rating: 5, color: "#3dffb5", spineStyle: "grid" },
  { id: 15, title: "Quiet Harbor",         title_en: "Quiet Harbor",         genre: "puzzle",     platform: "Mobile",  released: "2021-03-08", playtime: 14,  status: "cleared", rating: 3, color: "#7b5cff", spineStyle: "wave" },
  { id: 16, title: "Frostfall Tactics",    title_en: "Frostfall Tactics",    genre: "strategy",   platform: "PC",      released: "2024-10-05", playtime: 72,  status: "playing", rating: 5, color: "#00d9ff", spineStyle: "stripe" },
  { id: 17, title: "Mirror Maze",          title_en: "Mirror Maze",          genre: "puzzle",     platform: "Switch",  released: "2023-02-28", playtime: 11,  status: "cleared", rating: 4, color: "#c084fc", spineStyle: "grid" },
  { id: 18, title: "幽霊船の合言葉",        title_en: "Phantom Vessel",       genre: "adventure",  platform: "PS5",     released: "2025-01-17", playtime: 22,  status: "playing", rating: 4, color: "#5e60ce", spineStyle: "block" },
  { id: 19, title: "Hammer & Forge",       title_en: "Hammer & Forge",       genre: "simulation", platform: "PC",      released: "2020-11-30", playtime: 145, status: "cleared", rating: 4, color: "#ff7a3d", spineStyle: "split" },
  { id: 20, title: "Sky Pirate Marin",     title_en: "Sky Pirate Marin",     genre: "action",     platform: "PS4",     released: "2018-08-14", playtime: 53,  status: "cleared", rating: 5, color: "#ffd23f", spineStyle: "wave" },
  { id: 21, title: "Cassette Beast Club",  title_en: "Cassette Beast Club",  genre: "rpg",        platform: "Switch",  released: "2023-07-21", playtime: 0,   status: "backlog", rating: 0, color: "#3dffb5", spineStyle: "stripe" },
  { id: 22, title: "Loop Detective",       title_en: "Loop Detective",       genre: "puzzle",     platform: "PC",      released: "2024-04-02", playtime: 19,  status: "cleared", rating: 5, color: "#e63946", spineStyle: "block" },
  { id: 23, title: "Marble Engine",        title_en: "Marble Engine",        genre: "puzzle",     platform: "Mobile",  released: "2022-02-14", playtime: 6,   status: "cleared", rating: 3, color: "#a3a3a3", spineStyle: "grid" },
  { id: 24, title: "夜行列車RPG",          title_en: "Night Express",        genre: "rpg",        platform: "PC",      released: "2025-03-29", playtime: 4,   status: "playing", rating: 4, color: "#5e60ce", spineStyle: "split" }
];

window.GENRES = [
  { id: "rpg",        ja: "RPG",         en: "RPG",         color: "#7b5cff" },
  { id: "action",     ja: "アクション",   en: "Action",      color: "#e63946" },
  { id: "adventure",  ja: "アドベンチャー", en: "Adventure",   color: "#00d9ff" },
  { id: "racing",     ja: "レース",       en: "Racing",      color: "#ff3da5" },
  { id: "shooter",    ja: "シューター",   en: "Shooter",     color: "#3dffb5" },
  { id: "strategy",   ja: "ストラテジー",  en: "Strategy",    color: "#ffd23f" },
  { id: "simulation", ja: "シミュレーション", en: "Simulation", color: "#ff7a3d" },
  { id: "puzzle",     ja: "パズル",       en: "Puzzle",      color: "#c084fc" }
];

window.PLATFORMS = ["PS5", "PS4", "Switch", "Xbox", "PC", "Mobile"];

window.STATUSES = [
  { id: "backlog", ja: "積みゲー", en: "Backlog", color: "#a3a3a3" },
  { id: "playing", ja: "プレイ中", en: "Playing", color: "#ffd23f" },
  { id: "cleared", ja: "クリア",   en: "Cleared", color: "#3dffb5" },
  { id: "dropped", ja: "中断",     en: "Dropped", color: "#e63946" }
];

window.I18N = {
  ja: {
    appTitle: "MY GAME RACK",
    subtitle: "プレイ済みゲーム保管庫",
    addGame: "+ 新規追加",
    totalGames: "登録ゲーム",
    totalHours: "総プレイ時間",
    cleared: "クリア",
    playing: "プレイ中",
    backlog: "積みゲー",
    search: "タイトル検索...",
    allGenres: "すべてのジャンル",
    allPlatforms: "すべての機種",
    sortBy: "並び順",
    sortReleased: "購入年",
    sortPlaytime: "プレイ時間",
    sortRating: "評価",
    sortTitle: "タイトル",
    sortManual: "カスタム",
    rackView: "ラック表示",
    gridView: "グリッド表示",
    shelfA: "A棚 / RPG・アドベンチャー",
    shelfB: "B棚 / アクション・シューター",
    shelfC: "C棚 / その他",
    formTitle: "ゲームを追加",
    fTitle: "タイトル",
    fGenre: "ジャンル",
    fPlatform: "プレイ機種",
    fReleased: "購入日",
    fPlaytime: "プレイ時間（時間）",
    fStatus: "クリア状況",
    fRating: "評価",
    fImage: "パッケージ画像",
    fImageHint: "ドラッグ＆ドロップ または クリックで選択",
    save: "保存",
    cancel: "キャンセル",
    hours: "時間",
    released: "購入",
    playtime: "プレイ",
    rating: "評価",
    noImage: "NO IMAGE",
    flipBack: "戻る",
    delete: "削除",
    edit: "編集",
    dataSection: "データ",
    clearSamples: "サンプルを全削除",
    clearSamplesTitle: "サンプルゲームを削除しますか？",
    clearSamplesMsg: "初期サンプルとして登録されたゲームをすべて削除します。手動で追加したゲームは残ります。",
    clearSamplesConfirm: "サンプルを削除",
    exportBtn: "バックアップ書き出し",
    importBtn: "バックアップ読み込み",
    storageUsage: "保存容量",
    importTitle: "バックアップから復元しますか？",
    importMsg: "現在のラックを完全に置き換えます。先に書き出しておくことをおすすめします。",
    importInvalid: "ファイル形式が正しくありません。書き出した JSON ファイルを選んでください。",
    importConfirm: "復元する",
    quotaTitle: "保存容量の上限です",
    quotaMsg: "ブラウザの localStorage 上限に達しました。古いゲームを削除するか、画像を外して再保存してください。書き出し（バックアップ）は引き続き可能です。",
    quotaOk: "OK",
    shareSection: "共有",
    shareBtn: "共有URLを作成",
    screenshotBtn: "ラック画像を保存",
    shareTitle: "このラックを共有",
    shareMsg: "下のURLを送るだけで、相手はあなたのラックを閲覧できます。データはURL自体に含まれるので、URLを知っている人だけが見られます（誰でも転送できる点に注意）。",
    shareSize: "URLサイズ",
    shareSizeWarn: "8KB を超えています。チャットアプリによっては貼れない／途中で切れる可能性があります。",
    shareCopy: "URLをコピー",
    shareCopied: "コピーしました",
    shareClose: "閉じる",
    shareFailed: "共有URLの生成に失敗しました。",
    viewBanner: "🔗 共有リンクの閲覧モード",
    viewBannerSub: "他の人が共有したラックを表示しています。あなた自身の保存内容は変更されません。",
    importViewed: "自分のラックに取り込む",
    exitView: "閲覧モードを終了",
    importViewedTitle: "このラックを取り込みますか？",
    importViewedMsg: "現在のあなたのラックを、共有された内容で完全に置き換えます。先にバックアップを書き出しておくことをおすすめします。"
  },
  en: {
    appTitle: "MY GAME RACK",
    subtitle: "Personal Game Vault",
    addGame: "+ Add Game",
    totalGames: "Games",
    totalHours: "Total Hours",
    cleared: "Cleared",
    playing: "Playing",
    backlog: "Backlog",
    search: "Search title...",
    allGenres: "All genres",
    allPlatforms: "All platforms",
    sortBy: "Sort",
    sortReleased: "Purchased",
    sortPlaytime: "Playtime",
    sortRating: "Rating",
    sortTitle: "Title",
    sortManual: "Custom",
    rackView: "Rack",
    gridView: "Grid",
    shelfA: "Shelf A / RPG & Adventure",
    shelfB: "Shelf B / Action & Shooter",
    shelfC: "Shelf C / Other",
    formTitle: "Add Game",
    fTitle: "Title",
    fGenre: "Genre",
    fPlatform: "Platform",
    fReleased: "Purchase Date",
    fPlaytime: "Playtime (hours)",
    fStatus: "Status",
    fRating: "Rating",
    fImage: "Package art",
    fImageHint: "Drag & drop or click to upload",
    save: "Save",
    cancel: "Cancel",
    hours: "h",
    released: "Purchased",
    playtime: "Playtime",
    rating: "Rating",
    noImage: "NO IMAGE",
    flipBack: "Back",
    delete: "Delete",
    edit: "Edit",
    dataSection: "Data",
    clearSamples: "Clear samples",
    clearSamplesTitle: "Clear all sample games?",
    clearSamplesMsg: "All initial sample games will be removed. Games you added manually will be kept.",
    clearSamplesConfirm: "CLEAR",
    exportBtn: "Export backup",
    importBtn: "Import backup",
    storageUsage: "Storage",
    importTitle: "Restore from backup?",
    importMsg: "This will completely replace your current rack. Export first to keep a copy.",
    importInvalid: "Invalid file format. Please select a JSON file you previously exported.",
    importConfirm: "RESTORE",
    quotaTitle: "Storage limit reached",
    quotaMsg: "The browser localStorage quota is full. Delete some games or remove images, then try again. Export (backup) still works.",
    quotaOk: "OK",
    shareSection: "Share",
    shareBtn: "Create share URL",
    screenshotBtn: "Save rack image",
    shareTitle: "Share this rack",
    shareMsg: "Send the URL below — anyone with the link can view your rack. The data is embedded in the URL itself, so only people who have the URL can see it (note: it can be forwarded freely).",
    shareSize: "URL size",
    shareSizeWarn: "Over 8 KB — some chat apps may truncate or reject the URL.",
    shareCopy: "Copy URL",
    shareCopied: "Copied!",
    shareClose: "Close",
    shareFailed: "Failed to generate share URL.",
    viewBanner: "🔗 Shared rack — view mode",
    viewBannerSub: "You are viewing a rack someone shared with you. Your own saved rack is not affected.",
    importViewed: "Import to my rack",
    exitView: "Exit view mode",
    importViewedTitle: "Import this rack?",
    importViewedMsg: "Your current rack will be completely replaced with the shared content. Export your own backup first if you want to keep it."
  }
};
