// shared/data.js
// 全デザイン共通のデータ定義（サンプルゲーム・ジャンル・機種・ステータス・i18n）
// window 名前空間にぶら下げて、各 jsx から参照する。

window.SAMPLE_GAMES = [
  { id: 1,  title: "Neon Drifters",        title_en: "Neon Drifters",        genre: "racing",     platform: "PS5",     released: "2024-03-14", playtime: 42,  status: "cleared", rating: 5, color: "#ff3da5", spineStyle: "stripe" },
  { id: 2,  title: "クリスタル・ソナタ",    title_en: "Crystal Sonata",       genre: "rpg",        platform: "Switch",  released: "2023-11-09", playtime: 86,  status: "cleared", rating: 5, color: "#7b5cff", spineStyle: "block" },
  { id: 3,  title: "Hexblade Saga",        title_en: "Hexblade Saga",        genre: "rpg",        platform: "PC",      released: "2022-06-22", playtime: 124, status: "cleared", rating: 4, color: "#ffd23f", spineStyle: "split" },
  { id: 4,  title: "深海の灯",              title_en: "Lantern of the Deep",  genre: "adventure",  platform: "PS5",     released: "2024-08-30", playtime: 18,  status: "playing", rating: 4, color: "#00d9ff", spineStyle: "wave" },
  { id: 5,  title: "Pixel Pioneers",       title_en: "Pixel Pioneers",       genre: "strategy",   platform: "PC",      released: "2021-04-15", playtime: 210, status: "cleared", rating: 5, color: "#ff7a3d", spineStyle: "grid" },
  { id: 6,  title: "Star Captain Lyra",    title_en: "Star Captain Lyra",    genre: "shooter",    platform: "Xbox",    released: "2024-01-25", playtime: 31,  status: "cleared", rating: 4, color: "#3dffb5", spineStyle: "stripe" },
  { id: 7,  title: "Forgotten Wells",      title_en: "Forgotten Wells",      genre: "rpg",        platform: "PC",      released: "2025-02-11", playtime: 8,   status: "playing", rating: 3, color: "#c084fc", spineStyle: "block" },
  { id: 8,  title: "刀と霧",               title_en: "Steel and Mist",       genre: "action",     platform: "PS5",     released: "2023-05-19", playtime: 64,  status: "cleared", rating: 5, color: "#e63946", spineStyle: "split" },
  { id: 9,  title: "Sprocket City",        title_en: "Sprocket City",        genre: "simulation", platform: "Switch",  released: "2022-09-02", playtime: 92,  status: "cleared", rating: 4, color: "#ffd23f", spineStyle: "grid" },
  { id: 10, title: "Bunny Hop GP",         title_en: "Bunny Hop GP",         genre: "racing",     platform: "Switch",  released: "2020-07-10", playtime: 25,  status: "cleared", rating: 4, color: "#ff3da5", spineStyle: "stripe" },
  { id: 11, title: "Echoes of Halcyon",    title_en: "Echoes of Halcyon",    genre: "adventure",  platform: "PC",      released: "2023-10-20", playtime: 0,   status: "backlog", rating: 0, color: "#00d9ff", spineStyle: "wave" },
  { id: 12, title: "Tower of Iron",        title_en: "Tower of Iron",        genre: "action",     platform: "PS4",     released: "2019-12-05", playtime: 47,  status: "cleared", rating: 4, color: "#a3a3a3", spineStyle: "block" },
  { id: 13, title: "甘味喫茶ストーリー",    title_en: "Sweet Cafe Story",     genre: "simulation", platform: "Switch",  released: "2024-06-12", playtime: 38,  status: "playing", rating: 4, color: "#ff9eb5", spineStyle: "split" },
  { id: 14, title: "Rift Runners",         title_en: "Rift Runners",         genre: "shooter",    platform: "PC",      released: "2022-11-18", playtime: 156, status: "cleared", rating: 5, color: "#3dffb5", spineStyle: "grid" },
  { id: 15, title: "Quiet Harbor",         title_en: "Quiet Harbor",         genre: "puzzle",     platform: "Mobile",  released: "2021-03-08", playtime: 14,  status: "cleared", rating: 3, color: "#7b5cff", spineStyle: "wave" },
  { id: 16, title: "Frostfall Tactics",    title_en: "Frostfall Tactics",    genre: "strategy",   platform: "PC",      released: "2024-10-05", playtime: 72,  status: "playing", rating: 5, color: "#00d9ff", spineStyle: "stripe" },
  { id: 17, title: "Mirror Maze",          title_en: "Mirror Maze",          genre: "puzzle",     platform: "Switch",  released: "2023-02-28", playtime: 11,  status: "cleared", rating: 4, color: "#c084fc", spineStyle: "grid" },
  { id: 18, title: "幽霊船の合言葉",        title_en: "Phantom Vessel",       genre: "adventure",  platform: "PS5",     released: "2025-01-17", playtime: 22,  status: "playing", rating: 4, color: "#5e60ce", spineStyle: "block" },
  { id: 19, title: "Hammer & Forge",       title_en: "Hammer & Forge",       genre: "simulation", platform: "PC",      released: "2020-11-30", playtime: 145, status: "cleared", rating: 4, color: "#ff7a3d", spineStyle: "split" },
  { id: 20, title: "Sky Pirate Marin",     title_en: "Sky Pirate Marin",     genre: "action",     platform: "PS4",     released: "2018-08-14", playtime: 53,  status: "cleared", rating: 5, color: "#ffd23f", spineStyle: "wave" },
  { id: 21, title: "Cassette Beast Club",  title_en: "Cassette Beast Club",  genre: "rpg",        platform: "Switch",  released: "2023-07-21", playtime: 0,   status: "backlog", rating: 0, color: "#3dffb5", spineStyle: "stripe" },
  { id: 22, title: "Loop Detective",       title_en: "Loop Detective",       genre: "puzzle",     platform: "PC",      released: "2024-04-02", playtime: 19,  status: "cleared", rating: 5, color: "#e63946", spineStyle: "block" },
  { id: 23, title: "Marble Engine",        title_en: "Marble Engine",        genre: "puzzle",     platform: "Mobile",  released: "2022-02-14", playtime: 6,   status: "cleared", rating: 3, color: "#a3a3a3", spineStyle: "grid" },
  { id: 24, title: "夜行列車RPG",          title_en: "Night Express",        genre: "rpg",        platform: "PC",      released: "2025-03-29", playtime: 4,   status: "playing", rating: 4, color: "#5e60ce", spineStyle: "split" }
];

window.GENRES = [
  { id: "rpg",        ja: "RPG",         en: "RPG",         color: "#7b5cff" },
  { id: "action",     ja: "アクション",   en: "Action",      color: "#e63946" },
  { id: "adventure",  ja: "アドベンチャー", en: "Adventure",   color: "#00d9ff" },
  { id: "racing",     ja: "レース",       en: "Racing",      color: "#ff3da5" },
  { id: "shooter",    ja: "シューター",   en: "Shooter",     color: "#3dffb5" },
  { id: "strategy",   ja: "ストラテジー",  en: "Strategy",    color: "#ffd23f" },
  { id: "simulation", ja: "シミュレーション", en: "Simulation", color: "#ff7a3d" },
  { id: "puzzle",     ja: "パズル",       en: "Puzzle",      color: "#c084fc" }
];

window.PLATFORMS = ["PS5", "PS4", "Switch", "Xbox", "PC", "Mobile"];

window.STATUSES = [
  { id: "backlog", ja: "積みゲー", en: "Backlog", color: "#a3a3a3" },
  { id: "playing", ja: "プレイ中", en: "Playing", color: "#ffd23f" },
  { id: "cleared", ja: "クリア",   en: "Cleared", color: "#3dffb5" },
  { id: "dropped", ja: "中断",     en: "Dropped", color: "#e63946" }
];

window.I18N = {
  ja: {
    appTitle: "MY GAME RACK",
    subtitle: "プレイ済みゲーム保管庫",
    addGame: "+ 新規追加",
    totalGames: "登録ゲーム",
    totalHours: "総プレイ時間",
    cleared: "クリア",
    playing: "プレイ中",
    backlog: "積みゲー",
    search: "タイトル検索...",
    allGenres: "すべてのジャンル",
    allPlatforms: "すべての機種",
    sortBy: "並び順",
    sortReleased: "発売年",
    sortPlaytime: "プレイ時間",
    sortRating: "評価",
    sortTitle: "タイトル",
    rackView: "ラック表示",
    gridView: "グリッド表示",
    shelfA: "A棚 / RPG・アドベンチャー",
    shelfB: "B棚 / アクション・シューター",
    shelfC: "C棚 / その他",
    formTitle: "ゲームを追加",
    fTitle: "タイトル",
    fGenre: "ジャンル",
    fPlatform: "プレイ機種",
    fReleased: "発売日",
    fPlaytime: "プレイ時間（時間）",
    fStatus: "クリア状況",
    fRating: "評価",
    fImage: "パッケージ画像",
    fImageHint: "ドラッグ＆ドロップ または クリックで選択",
    save: "保存",
    cancel: "キャンセル",
    hours: "時間",
    released: "発売",
    playtime: "プレイ",
    rating: "評価",
    noImage: "NO IMAGE",
    flipBack: "戻る",
    delete: "削除",
    edit: "編集"
  },
  en: {
    appTitle: "MY GAME RACK",
    subtitle: "Personal Game Vault",
    addGame: "+ Add Game",
    totalGames: "Games",
    totalHours: "Total Hours",
    cleared: "Cleared",
    playing: "Playing",
    backlog: "Backlog",
    search: "Search title...",
    allGenres: "All genres",
    allPlatforms: "All platforms",
    sortBy: "Sort",
    sortReleased: "Released",
    sortPlaytime: "Playtime",
    sortRating: "Rating",
    sortTitle: "Title",
    rackView: "Rack",
    gridView: "Grid",
    shelfA: "Shelf A / RPG & Adventure",
    shelfB: "Shelf B / Action & Shooter",
    shelfC: "Shelf C / Other",
    formTitle: "Add Game",
    fTitle: "Title",
    fGenre: "Genre",
    fPlatform: "Platform",
    fReleased: "Released",
    fPlaytime: "Playtime (hours)",
    fStatus: "Status",
    fRating: "Rating",
    fImage: "Package art",
    fImageHint: "Drag & drop or click to upload",
    save: "Save",
    cancel: "Cancel",
    hours: "h",
    released: "Released",
    playtime: "Playtime",
    rating: "Rating",
    noImage: "NO IMAGE",
    flipBack: "Back",
    delete: "Delete",
    edit: "Edit"
  }
};
